apiVersion: eksctl.io/v1alpha4
kind: ClusterConfig
metadata:
  name: aae-eks
  region: us-east-1

vpc:
  cidr: 10.10.0.0/16
  autoAllocateIPv6: true

nodeGroups:
  - name: ng-1
    instanceType: m4.4xlarge
    minSize: 1
    maxSize: 5
    volumeSize: 100
    volumeType: gp2
    ssh: # import public key from file
      publicKeyPath: ~/.ssh/ec2_id_rsa.pub

